#!/bin/bash
clear

# System Report generated by USERNAME, DATE/TIME
echo "System Report generated by $(whoami), $(date +"%Y-%m-%d %H:%M:%S")"
echo

# System Information
echo "System Information"
echo "------------------"
echo "Hostname: $(hostname)"
echo "OS: $(source /etc/os-release && echo $PRETTY_NAME)"
echo "Uptime: $(uptime -p)"
echo

# Hardware Information
echo "Hardware Information"
echo "--------------------"
echo "CPU: $(lscpu | grep 'Model name' | awk -F': ' '{print $2}' | sed 's/^ *//')"
echo "RAM: $(free -h | awk '/^Mem:/ {print $2}')"
echo "Disk(s):"
lsblk -d -o NAME,SIZE | grep -v "NAME" | awk '{print "Disk: " $1 " Size: " $2}'
echo "Video: $(lspci | grep -i vga | awk -F: '{print $3}' | sed 's/^ //')"
echo

# Network Information
echo "Network Information"
echo "-------------------"
echo "FQDN: $(hostname -f)"
echo "Host Address: $(ip a | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | head -n 1)"
echo "Gateway IP: $(ip r | grep default | awk '{print $3}')"
echo "DNS Server: $(grep nameserver /etc/resolv.conf | awk '{print $2}' | head -n 1)"
echo

# System Status
echo "System Status"
echo "-------------"
echo "Users Logged In: $(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')"
echo "Disk Space:"
df -h | awk '/^\/dev/ {print $6 " " $4}'
echo "Process Count: $(ps -e | wc -l)"
echo "Load Averages: $(uptime | awk -F'average: ' '{print $2}')"
echo "Listening Network Ports: $(ss -tuln | awk '/LISTEN/ {print $5}' | cut -d':' -f2 | sort -n | uniq | tr '\n' ',' | sed 's/,$//')"
echo "UFW Status: $(sudo ufw status | grep -w "Status" | awk '{print $2}')"
