#!/bin/bash
# Clear the terminal screen 
clear

# Print a header for the system report, including the username and current date/time.
echo "System Report generated by $(whoami), $(date +"%Y-%m-%d %H:%M:%S")"
echo

# Display basic system information.
echo "System Information"
echo "------------------"
# Show the computer's name.
echo "Hostname: $(hostname)"
# Show the operating system name.
echo "OS: $(source /etc/os-release && echo $PRETTY_NAME)"
# Show how long the system has been running.
echo "Uptime: $(uptime -p)"
echo

# Display hardware details.
echo "Hardware Information"
echo "--------------------"
# Show the processor type.
echo "CPU: $(lscpu | grep 'Model name' | awk -F': ' '{print $2}' | sed 's/^ *//')"
# Show the total memory RAM size.
echo "RAM: $(free -h | awk '/^Mem:/ {print $2}')"
# List all disks and their sizes.
echo "Disk(s):"
lsblk -d -o NAME,SIZE | grep -v "NAME" | awk '{print "Disk: " $1 " Size: " $2}'
# Show the graphics card.
echo "Video: $(lspci | grep -i vga | awk -F: '{print $3}' | sed 's/^ //')"
echo

# Display network information.
echo "Network Information"
echo "-------------------"
# Show the full domain name of the system.
echo "FQDN: $(hostname -f)"
# Show the IP address.
echo "Host Address: $(ip a | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | head -n 1)"
# Show the Gateway address.
echo "Gateway IP: $(ip r | grep default | awk '{print $3}')"
# Show the DNS server used for internet.
echo "DNS Server: $(grep nameserver /etc/resolv.conf | awk '{print $2}' | head -n 1)"
echo

# Display the current status of the system.
echo "System Status"
echo "-------------"
# Show who is logged in.
echo "Users Logged In: $(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')"
# Show free disk space for each partition.
echo "Disk Space:"
df -h | awk '/^\/dev/ {print $6 " " $4}'
# Show the total number of running processes.
echo "Process Count: $(ps -e | wc -l)"
# Show how busy the system is.
echo "Load Averages: $(uptime | awk -F'average: ' '{print $2}')"
# Show ports that are listening.
echo "Listening Network Ports: $(ss -tuln | awk '/LISTEN/ {print $5}' | cut -d':' -f2 | sort -n | uniq | tr '\n' ',' | sed 's/,$//')"
# Show if the firewall is active or inactive.
echo "UFW Status: $(sudo ufw status | grep -w "Status" | awk '{print $2}')"
